import SwiftUI


struct RecipeGroup: Codable, Identifiable {
    typealias ID = String
    let id: ID
    let items: [String]
    let color: RawColor
    let iconName: String
}

let defaultRecipeContent: [RecipeGroup] = [
    .init(id: "Gluten Free", items: ["wheat","barley","rye","triticale","bulgur","farina","kamut","semolina","spelt","durum","graham flour","malt","brewer's yeast","wheat starch","wheat germ","wheat bran","wheat protein isolate","hydrolyzed wheat protein","textured wheat protein","modified wheat starch","couscous","einkorn","emmer","matzo","orzo","panko breadcrumbs","wheat berries","wheat grass","wheat malt","wheat sprouts","wheatgrass","wheatgrass extract","wheat-based maltodextrin","wheat-based dextrin","wheat-based monosodium glutamate","msg","wheat-based vinegar","wheat-based artificial flavoring","wheat-based natural flavoring","wheat-based thickening agents","wheat-based stabilizing agents","wheat-based emulsifiers","wheat-based humectants","farro","seitan","mirin","teriyaki sauce","soy sauce","worcestershire sauce","beer","ale","lager","stout","porter","malt vinegar","malted milk powder","oat bran","oatmeal","oat flour","barley malt","barley grass","barley flour","barley extract","brown rice syrup","barley enzymes","bulgur wheat","graham","maltodextrin","rye flour","tabouli","udon noodles","wheat flour","textured vegetable protein","all-purpose flour","bleached flour","bread flour","enriched flour","hordeum vulgare","hydrolyzed wheat starch","pasta","secale cereale","triticum spelta","triticum vulgare","wheat protein"]
          , color: RawColor(r: 0.94, g: 0.4, b: 0.3), iconName: "🍞"),
    .init(id: "Celiac Friendly", items: ["triticum vulgare","triticale","hordeum vulgare","secale cereale","rye","barley","triticum spelta","wheat protein","hydrolyzed wheat protein","wheat starch","hydrolyzed wheat starch","wheat flour","bread flour","bleached flour","bulgur","malt","couscous","farina","pasta","seitan","wheat","durum","graham flour","semolina","farro","processed cheese"]
          , color: RawColor(r: 0.95, g: 0.56, b: 0.14), iconName: "🌾"),
    .init(id: "Lactose Free", items: ["lactose","whey","casein","butter","milk powder","milk solids","milk protein","buttermilk","cheese","cream","curd","dairy solids","evaporated milk","ghee","half-and-half","ice cream","kefir","nonfat dry milk","ricotta cheese","sherbet","sour cream","yogurt","condensed milk","cream cheese","skim milk powder","cheese sauce","cheese spread","malted milk","milk fat","milk sugar","yogurt powder","butter flavor","lactalbumin","lactoferrin","lactoglobulin","milk derivatives","milk protein isolate","quark","recaldent","whey protein","béchamel sauce","caramel","custard","dulce de leche","hydrolyzed casein","lactulose","margarine","nougat","panna cotta","pudding","toffee","whey protein isolate","casein hydrolysate","dairy creamer","goat's milk","lactate solids","mocha","paneer","protein powder","ricotta salata","sheep's milk","sour milk","whipped cream","acidophilus milk","chevre","chocolate milk","cottage cheese","cream of tartar","flan","gorgonzola","havarti","instant breakfast","kugel","milk chocolate","milk bread","milk pudding","queso blanco","queso fresco","sweetened condensed milk","blue cheese","cream of wheat","feta cheese","fromage blanc","marscapone","neufchâtel cheese","pecorino romano","pizza cheese","powdered milk","quiche","tzatziki","american cheese","butterscotch","creamed corn","fried ice cream","italian dressing","malted milk balls","mocha flavoring","pancake mix"], color: RawColor(r: 0.3, g: 0.4, b: 0.89), iconName: "🥛"),
    .init(id: "Dairy Free", items: ["lactose","whey","casein","butter","milk powder","milk solids","milk protein","buttermilk","cheese","cream","curd","dairy solids","evaporated milk","ghee","half-and-half","ice cream","kefir","nonfat dry milk","ricotta cheese","sherbet","sour cream","yogurt","condensed milk","cream cheese","skim milk powder","cheese sauce","cheese spread","malted milk","milk fat","milk sugar","yogurt powder","butter flavor","lactalbumin","lactoferrin","lactoglobulin","milk derivatives","milk protein isolate","quark","recaldent","whey protein","béchamel sauce","caramel","custard","dulce de leche","hydrolyzed casein","lactulose","margarine","nougat","panna cotta","pudding","toffee","whey protein isolate","casein hydrolysate","dairy creamer","goat's milk","lactate solids","mocha","paneer","protein powder","ricotta salata","sheep's milk","sour milk","whipped cream","acidophilus milk","chevre","chocolate milk","cottage cheese","cream of tartar","flan","gorgonzola","havarti","instant breakfast","kugel","milk chocolate","milk bread","milk pudding","queso blanco","queso fresco","sweetened condensed milk","blue cheese","cream of wheat","feta cheese","fromage blanc","marscapone","neufchâtel cheese","pecorino romano","pizza cheese","powdered milk","quiche","tzatziki","american cheese","butterscotch","creamed corn","fried ice cream","italian dressing","malted milk balls","mocha flavoring","pancake mix","butter,","buttermilk,","cheese,","casein,","caseinate,","cream,","curds,","ghee,","half and half,","lactalbumin,","lactate,","lactoglobulin,","lactose,","milk,","milkfat,","sour cream,","whey,","yogurt,","anhydrous milkfat,","artificial butter flavor,","butter esters,","butter oil,","calcium caseinate,","caramel color,","curd,","custard,","delactosed whey,","demineralized whey,","dry milk powder,","dry milk solids,","evaporated milk,","flavorings,","high protein flour,","hydrolyzed casein,","hydrolyzed milk protein,","iron caseinate,","lactic acid starter culture,","lactitol,","malted milk,","milk derivative,","modified milk ingredients,","natural butter flavor,","nonfat milk,","nougat,","pudding,","recaldent,","rennet,","simplesse,","sodium caseinate,","tagatose,","whey protein concentrate,","whey protein hydrolysate,","whipped cream,","xanthan gum"], color: RawColor(r: 0.2, g: 0.6, b: 0.97), iconName: "🥤"),
    .init(id: "Nut Free", items: ["almond","amaretto","anacardium nuts","beech nuts","brazil nuts","butternut","cashew","chestnut","chinquapin","coconut","filbert","hazelnut","gianduja","ginkgo nuts","hickory nuts","karite","lichee nuts","macadamia nuts","marzipan","almond paste","nangai nuts","nut butter","peanut butter","almond butter","nut extracts","nut meal","nut oils","nut paste","nut pieces","nutella","pecan","pine nuts","pistachio","praline","shea nuts","walnut","arachis oil","artificial nuts","chestnut paste","gomasio","granola","halva","hazelnut oil","nut nougat","nut powders","nut syrup","peanut flour","pesto sauce","poppy seed dressing","sesame seeds and sesame oil","sunflower seed butter","tahini","treenuts","bee pollen","candlenuts","caponata","chia seeds","dukkah","flaxseeds","goji berries","horchata","krembo","linseeds","muesli","oatmeal","pine nut oil","quinoa"], color: RawColor(r: 0.68, g: 0.5, b: 0.38), iconName: "🥜"),
    .init(id: "Soy Free", items: ["soybeans","soy sauce","edamame","miso","natto","tempeh","tofu","shoyu sauce","tamari","kinako","textured vegetable protein","tvp","hydrolyzed soy protein","soy lecithin","vegetable oil","vegetable broth","vegetable gum","vegetable starch","glycerin","glycerol","mono-diglyceride","monosodium glutamate","msg","natural flavoring","artificial flavoring","bouillon","carrageenan","guar gum","carob","emulsifiers","stabilizers","thickeners","vitamin e","yeast extract","margarine","non-dairy creamers","worcestershire sauce","cheese substitutes","salad dressings","baked goods","canned foods","processed meats","protein bars"], color: RawColor(r: 0.2, g: 0.76, b: 0.4), iconName: "🫘"),
]

